### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by lianfulei** [prometheus/memcached_exporter#91]
make
>> checking code style
>> checking license header
>> running golangci-lint
GO111MODULE=on go list -e -compiled -test=true -export=false -deps=true -find=false -tags= -- ./... > /dev/null
GO111MODULE=on /root/go/bin/golangci-lint run  ./...
>> running check for unused/missing packages in go.mod
GO111MODULE=on go mod tidy
>> running check for unused packages in vendor/
GO111MODULE=on go mod vendor
>> building binaries
GO111MODULE=on /root/go/bin/promu build --prefix /root/software/memcached_exporter 
 >   memcached_exporter
>> running all tests
GO111MODULE=on go test -race  -mod=vendor ./...
--- FAIL: TestAcceptance (0.12s)
panic: runtime error: slice bounds out of range [:3] with length 0 [recovered]
	panic: runtime error: slice bounds out of range [:3] with length 0

goroutine 8 [running]:
testing.tRunner.func1.1(0xc1c2e0, 0xc000025820)
	/root/go/src/testing/testing.go:988 +0x452
testing.tRunner.func1(0xc0000acea0)
	/root/go/src/testing/testing.go:991 +0x600
panic(0xc1c2e0, 0xc000025820)
	/root/go/src/runtime/panic.go:975 +0x3e3
github.com/prometheus/memcached_exporter.TestAcceptance(0xc0000acea0)
	/root/software/memcached_exporter/main_test.go:172 +0x2495
testing.tRunner(0xc0000acea0, 0xc7e500)
	/root/go/src/testing/testing.go:1039 +0x1ec
created by testing.(*T).Run
	/root/go/src/testing/testing.go:1090 +0x701
FAIL	github.com/prometheus/memcached_exporter	0.145s
FAIL
make: *** [common-test] Error 1

**Comment by lianfulei** [comment]
sove
